# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

jvm_auto_instrumentation_agent_path = /usr/lib/opentelemetry/jvm/java6-agent.jar
jvm_auto_instrumentation_minimum_java_major_version = 6
