# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

ARG base_image="node:22.15.0-bookworm-slim"
FROM ${base_image}

ARG injector_binary
RUN if [ -z "$injector_binary" ]; then \
      echo "Error: build argument injector_binary is required but not set."; \
      exit 1; \
    fi

ARG create_sdk_dummy_files_script
RUN if [ -z "$create_sdk_dummy_files_script" ]; then \
      echo "Error: build argument create_sdk_dummy_files_script is required but not set."; \
      exit 1; \
    fi

WORKDIR /usr/src/otel/injector/

COPY test/apps/node_js app

COPY test/scripts/run-tests-within-container.sh scripts/
COPY test/scripts/create-*.sh scripts/
COPY test/scripts/*.tests scripts/

RUN ${create_sdk_dummy_files_script}

COPY dist/${injector_binary} /injector/libotelinject.so

USER node
CMD ["scripts/run-tests-within-container.sh"]
