name: Automation - Prepare Release

on:
  workflow_dispatch:
    # Determine the version number that will be assigned to the release.
    inputs:
      version:
        required: true
        description: Release version or release candidate version (like v0.70.0 or v0.70.0-20260109)
permissions:
  contents: read
jobs:
  # Releasing opentelemetry-injector
  prepare-release:
    permissions:
      contents: write # required for pushing changes in prepare-release.sh
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: otelbot-token
        with:
          app-id: ${{ vars.OTELBOT_APP_ID }}
          private-key: ${{ secrets.OTELBOT_PRIVATE_KEY }}
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: "1.26.5"
          cache: false
      - name: Prepare release for injector
        env:
          GITHUB_TOKEN: ${{ steps.otelbot-token.outputs.token }}
          REPO: open-telemetry/opentelemetry-injector
          VERSION: ${{ inputs.version }}
        run: ./.github/workflows/scripts/prepare-release.sh
